<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>

        <!-- 定义 Kaitai 相关路径 -->
        <KaitaiSourceDir>$(MSBuildThisFileDirectory)../../common</KaitaiSourceDir>
        <KaitaiOutputDir>$(MSBuildThisFileDirectory)Service/Kaitai</KaitaiOutputDir>
        <KaitaiCompiler>ksc</KaitaiCompiler>
    </PropertyGroup>

    <ItemGroup>
        <AvaloniaResource Include="Assets\**\*" />
        <Compile Include="$(KaitaiOutputDir)/**/*.cs" />
        <Compile Update="Assets\Resources.Designer.cs">
          <DesignTime>True</DesignTime>
          <AutoGen>True</AutoGen>
          <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
        <Compile Update="Assets\Resources.zh-CN.Designer.cs">
          <DesignTime>True</DesignTime>
          <AutoGen>True</AutoGen>
          <DependentUpon>Resources.zh-CN.resx</DependentUpon>
        </Compile>
        <Compile Update="Assets\Resources.Designer.cs">
          <DesignTime>True</DesignTime>
          <AutoGen>True</AutoGen>
          <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" />
        <PackageReference Include="Avalonia.Themes.Fluent" />
        <PackageReference Include="Avalonia.Fonts.Inter" />
        <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
        <PackageReference Include="Avalonia.Diagnostics">
            <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
            <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
        </PackageReference>
        <PackageReference Include="CommunityToolkit.Mvvm" />
        <PackageReference Include="KaitaiStruct.Runtime.CSharp" />
        <PackageReference Include="LiveCharts" />
        <PackageReference Include="LiveChartsCore.SkiaSharpView.Avalonia" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Update="Assets\Resources.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Resources.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Service\Kaitai\" />
    </ItemGroup>
    
    <!-- 定义 Kaitai 相关任务 -->
    <Target Name="KaitaiCompile" AfterTargets="Build" Inputs="$(KaitaiSourceDir)/*.ksy" Outputs="$(KaitaiOutputDir)/*.cs">
        <MakeDir Directories="$(KaitaiOutputDir)" />
        <Exec Command="$(KaitaiCompiler) -t csharp --outdir $(KaitaiOutputDir) $(KaitaiSourceDir)/*.ksy"/>
        <Message Text="Kaitai compiled successfully." Importance="high"/>
    </Target>
</Project>
