#Generated by Fabric Compiler ( version 2022.2-SP6.4 <build 146967> ) at Thu Oct 30 18:07:10 2025

add_design "C:/Users/32188/Desktop/osc/pds/source/.v/adc_fft_top.v"
add_design "C:/Users/32188/Desktop/osc/pds/source/.v/adc_capture.v"
add_design "C:/Users/32188/Desktop/osc/pds/source/.v/data_preprocessor.v"
add_design "C:/Users/32188/Desktop/osc/pds/source/.v/fft_processor.v"
add_design "C:/Users/32188/Desktop/osc/pds/source/.v/pll.v"
add_design "C:/Users/32188/Desktop/osc/pds/source/.v/result_processor.v"
add_constraint "C:/Users/32188/Desktop/adcfft/.fdc/yueshu.fdc"
add_design C:/Users/32188/Desktop/osc/pds/ipcore/u_pango_adc/u_pango_adc.idf
add_design C:/Users/32188/Desktop/osc/pds/ipcore/u_pango_fft/u_pango_fft.idf
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module adc_fft_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module adc_fft_top
set_arch -family Logos2 -device PG2L100H -speedgrade -6 -package FBG676
compile -top_module adc_fft_top
synthesize -ads -selected_syn_tool_opt 2 
dev_map 
pnr 
report_timing 
gen_bit_stream 
